[pytest]
addopts = -v
pythonpath = .
markers =
    unit: unit test
    integration: integration test
    e2e: end-2-end test
    
    katalog_01: User Story marker
    katalog_02: User Story marker
    katalog_03: User Story marker
    addbok_01: User Story marker
    minbok_01: User Story marker
    stat_01: User Story marker